language: node_js
node_js:
- '8.11.2'

install:
  - npm install
  - npm install -g codecov

before_script:
  - npm run build
  
script:
  - npm run test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov